# Generated by Django 6.0.1 on 2026-02-05 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DanhMuc',
            fields=[
                ('MaDanhMuc', models.AutoField(primary_key=True, serialize=False)),
                ('TenDanhMuc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DoanhThu',
            fields=[
                ('Ngay', models.DateField(primary_key=True, serialize=False)),
                ('TongDon', models.IntegerField()),
                ('TongSoLuong', models.IntegerField()),
                ('TongDoanhThu', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('MaKH', models.AutoField(primary_key=True, serialize=False)),
                ('HoTen', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('MatKhau', models.CharField(max_length=100)),
                ('SoDienThoai', models.CharField(max_length=15)),
                ('DiaChi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('MaNV', models.AutoField(primary_key=True, serialize=False)),
                ('HoTen', models.CharField(max_length=100)),
                ('ChucVu', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=100)),
                ('MatKhau', models.CharField(max_length=100)),
                ('TinhTrang', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('MaSize', models.AutoField(primary_key=True, serialize=False)),
                ('TenSize', models.CharField(max_length=20)),
                ('GiaTang', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('MaDon', models.AutoField(primary_key=True, serialize=False)),
                ('NgayDat', models.DateField(auto_now_add=True)),
                ('TongTien', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TrangThai', models.CharField(max_length=50)),
                ('MaKH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.khachhang')),
                ('MaNV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.nhanvien')),
            ],
        ),
        migrations.CreateModel(
            name='ThucDon',
            fields=[
                ('MaMon', models.AutoField(primary_key=True, serialize=False)),
                ('TenMon', models.CharField(max_length=100)),
                ('MoTa', models.TextField(blank=True, null=True)),
                ('Gia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('HinhAnh', models.CharField(blank=True, max_length=255, null=True)),
                ('TinhTrang', models.BooleanField(default=True)),
                ('SanPhamNoiBat', models.BooleanField(default=False)),
                ('CoSize', models.BooleanField(default=False)),
                ('MaDanhMuc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.danhmuc')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietDonHang',
            fields=[
                ('MaChiTiet', models.AutoField(primary_key=True, serialize=False)),
                ('SoLuong', models.IntegerField(default=1)),
                ('DonGia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PhuThu', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ThanhTien', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('MaDon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.donhang')),
                ('MaSize', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.size')),
                ('MaMon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.thucdon')),
            ],
        ),
    ]
