# Generated by Django 6.0.1 on 2026-03-11 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChiTietDon',
            fields=[
                ('mact', models.AutoField(primary_key=True, serialize=False)),
                ('soluong', models.IntegerField()),
                ('thanhtien', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gia_luc_dat', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'chitietdon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DanhMuc',
            fields=[
                ('madanhmuc', models.AutoField(primary_key=True, serialize=False)),
                ('tendanhmuc', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'danhmuc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('madon', models.AutoField(primary_key=True, serialize=False)),
                ('thoigiandat', models.DateTimeField(auto_now_add=True)),
                ('trangthai', models.CharField(default='DANGXULY', max_length=50)),
                ('tongtien', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('loaidon', models.CharField(default='ONLINE', max_length=20)),
            ],
            options={
                'db_table': 'donhang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('makh', models.AutoField(primary_key=True, serialize=False)),
                ('tenkh', models.CharField(max_length=200)),
                ('sodienthoai', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('diachi', models.TextField(blank=True, null=True)),
                ('geom', models.TextField()),
            ],
            options={
                'db_table': 'khachhang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mon',
            fields=[
                ('mamon', models.AutoField(primary_key=True, serialize=False)),
                ('tenmon', models.CharField(max_length=200)),
                ('giatien', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mota', models.TextField(blank=True, null=True)),
                ('hinhanh', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('manv', models.AutoField(primary_key=True, serialize=False)),
                ('tennv', models.CharField(max_length=200)),
                ('sodienthoai', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'nhanvien',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuanCafe',
            fields=[
                ('macafe', models.AutoField(primary_key=True, serialize=False)),
                ('tencafe', models.CharField(max_length=200)),
                ('diachi', models.TextField(blank=True, null=True)),
                ('sodienthoai', models.CharField(blank=True, max_length=15, null=True)),
                ('geom', models.TextField()),
            ],
            options={
                'db_table': 'quancafe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chi_nhanh', models.CharField(choices=[('Q3', 'Quận 3'), ('Q7', 'Quận 7')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
